apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: 'https://kubernetes-sigs.github.io/external-dns/'
    chart: external-dns
    targetRevision: "*"

    helm:
      values: |
        provider:
          name: webhook
          webhook:
            image:
              repository: ghcr.io/home-operations/external-dns-unifi-webhook
              tag: main
              pullPolicy: IfNotPresent

            env:
              - name: UNIFI_HOST
                value: "https://10.74.1.1"

              - name: UNIFI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: unifi-dns-secret
                    key: UNIFI_API_KEY

              - name: UNIFI_SKIP_TLS_VERIFY
                value: "true"

            livenessProbe:
              httpGet:
                path: /healthz
                port: http-webhook
              initialDelaySeconds: 10
              timeoutSeconds: 5

            readinessProbe:
              httpGet:
                path: /readyz
                port: http-webhook
              initialDelaySeconds: 10
              timeoutSeconds: 5

        sources:
          - service
          - ingress

        domainFilters:
          - ntsme.org

        policy: sync

        registry: txt
        txtOwnerId: k8s-cluster

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

