apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    # targetRevision is omitted, so Argo CD grabs the latest chart automatically
    helm:
      values: |
        controller:
          enabled: true
        speaker:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-network-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.74.5.100-10.74.5.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-network-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - home-network-pool
